GET http://localhost:8080/api/users/?page=1

###
# @name createUser
POST http://localhost:8080/api/user
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "johx.sdoe@example.com",
    "password": "my_secure_password"
}

@userId = {{ createUser.response.body.data.id }}

###

GET http://localhost:8080/api/user/{{ userId }}

###

PATCH http://localhost:8080/api/user/{{ userId }}

{
    "first_name": "Julio",
    "last_name": "Alves",
    "email": "julioOlder@example.com",
    "password": "another_password"
}

###

DELETE http://localhost:8080/api/user/{{ userId }}
