version: '4.0'

services:

  server:
    build: .
    ports:
      - "8080:8080"
      - "50051:50051" 
    volumes:
      - .:/app
    command: air
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: